project_id = "npekpdkywsneylddzzuu"

[functions]
  [functions.auth-email-hook]
    verify_jwt = false
  [functions.create-account]
    verify_jwt = false
  [functions.daily-doc-reminders]
    verify_jwt = false
  [functions.gestionar-baja]
    verify_jwt = false
  [functions.request-password-reset]
    verify_jwt = false
  [functions.test-email]
    verify_jwt = false
